---
abstract: 'transform :list regions into =over/=back to save typing'
author:
  - 'Ricardo SIGNES <cpan@semiotic.systems>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Pod::Elemental: '0'
  Pod::Elemental::Transformer::Pod5: '0'
  Test::Differences: '0'
  Test::Fatal: '0'
  Test::More: '0.96'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.78'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Elemental-Transformer-List
requires:
  Moose: '0'
  Pod::Elemental::Element::Pod5::Command: '0'
  Pod::Elemental::Transformer: '0.101620'
  Pod::Elemental::Types: '0'
  namespace::autoclean: '0'
  perl: '5.012'
resources:
  bugtracker: https://github.com/rjbs/Pod-Elemental-Transformer-List/issues
  homepage: https://github.com/rjbs/Pod-Elemental-Transformer-List
  repository: https://github.com/rjbs/Pod-Elemental-Transformer-List.git
version: '0.102001'
x_Dist_Zilla:
  perl:
    version: '5.037002'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: '@RJBS/Git::GatherDir'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RJBS/CheckPrereqsIndexed'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@RJBS/CheckExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 0
          check_all_prereqs: 0
          modules:
            - Dist::Zilla::PluginBundle::RJBS
          phase: build
          run_under_travis: 0
          skip: []
      name: '@RJBS/RJBS-Outdated'
      version: '0.057'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 0
          modules: []
          phase: release
          run_under_travis: 0
          skip:
            - Dist::Zilla::Plugin::RJBSMisc
      name: '@RJBS/CPAN-Outdated'
      version: '0.057'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Filter/PruneCruft'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Filter/ManifestSkip'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Filter/MetaYAML'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Filter/License'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Filter/Readme'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Filter/ExecDir'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Filter/ShareDir'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Filter/Manifest'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Filter/TestRelease'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Filter/ConfirmRelease'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Filter/UploadToCPAN'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 9
      name: '@RJBS/MakeMaker'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RJBS/AutoPrereqs'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: 1
          version_regexp: (?^:^([0-9]+\.[0-9]+)$)
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.38.0
          repo_root: .
      name: '@RJBS/Git::NextVersion'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@RJBS/Test::ChangesHasContent'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@RJBS/Test::ReportPrereqs'
      version: '0.028'
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@RJBS/Git::Remote::Check'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@RJBS/TestMoreWithSubtests'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@RJBS'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.018'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.018'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@RJBS/SingleEncoding'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Name
              name: '@RJBS/Name'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Version
              name: '@RJBS/Version'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Region
              name: '@RJBS/Prelude'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Synopsis'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Description'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Overview'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Generic
              name: '@RJBS/Stability'
              version: '4.018'
            -
              class: Pod::Weaver::Section::GenerateSection
              name: '@RJBS/PerlSupport'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Collect
              name: Attributes
              version: '4.018'
            -
              class: Pod::Weaver::Section::Collect
              name: Methods
              version: '4.018'
            -
              class: Pod::Weaver::Section::Collect
              name: Functions
              version: '4.018'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@RJBS/Leftovers'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Region
              name: '@RJBS/postlude'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Authors
              name: '@RJBS/Authors'
              version: '4.018'
            -
              class: Pod::Weaver::Section::Contributors
              name: '@RJBS/Contributors'
              version: '0.009'
            -
              class: Pod::Weaver::Section::Legal
              name: '@RJBS/Legal'
              version: '4.018'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@RJBS/List'
              version: '4.018'
      name: '@RJBS/PodWeaver'
      version: '4.009'
    -
      class: Dist::Zilla::Plugin::RJBSMisc
      name: '@RJBS/RJBSMisc'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@RJBS/GithubMeta'
      version: '0.58'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.38.0
          repo_root: .
      name: '@RJBS/@Git/Check'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%V%n%n%c
          signoff: 0
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.38.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@RJBS/@Git/Commit'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: '0.102001'
          tag_format: '%v'
          tag_message: v%V
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.38.0
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@RJBS/@Git/Tag'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - 'github :'
          remotes_must_exist: 0
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.38.0
          repo_root: .
      name: '@RJBS/@Git/Push'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          git_version: 2.38.0
          include_authors: 0
          include_releaser: 1
          order_by: name
          paths: []
      name: '@RJBS/Git::Contributors'
      version: '0.036'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.029'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.029'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: '6.029'
x_contributors:
  - 'Alex Peters <lxp@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
  - 'Justin Cook <jcook@cray.com>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Ricardo Signes <rjbs@semiotic.systems>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
x_generated_by_perl: v5.37.2
x_rjbs_perl_window: long-term
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
